name: Daily File Uploader

on:
  schedule:
    - cron: '*/3 * * * *' # Runs every 3 minutes

jobs:
  upload_file:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Modify or Add a File
      - name: Add or Modify a File
        run: |
          echo "This file was uploaded on $(date)" > 1.two-sum.cpp
          git add 1.two-sum.cpp

      # Step 3: Commit the Change
      - name: Commit Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Daily file update on $(date)" || echo "No changes to commit"

      # Step 4: Push Changes
      - name: Push Changes
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
